services:
  mysql:
    image: mysql:latest
    container_name: card_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: CARDDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: card_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak-config.json:/opt/keycloak/data/import/keycloak-config.json
    command:
      - start-dev
      - --import-realm
    networks:
      - keycloak-network

volumes:
  mysql_data:

networks:
  keycloak-network:
    driver: bridge